# Generated by Django 3.0.8 on 2020-09-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_level_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='second_level_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='third_level_price',
            field=models.FloatField(null=True),
        ),
    ]
