# Generated by Django 3.0.8 on 2020-09-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20200910_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='first_level_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='second_level_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='third_level_price',
        ),
    ]
