# Generated by Django 3.0.8 on 2020-09-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='options',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('1', 'shirts'), ('2', 'T-shirts'), ('3', 'Pants'), ('4', 'Hoodies')], max_length=40, null=True),
        ),
    ]
