# Generated by Django 3.0.8 on 2020-09-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20200910_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('1', 'shirts'), ('2', 'T-shirts'), ('3', 'Pants'), ('4', 'Hoodies'), ('5', 'Shoes')], max_length=40, null=True),
        ),
    ]
