# Generated by Django 3.0.8 on 2020-09-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20200910_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shirt-category', 'shirts'), ('Tshirt-category', 'T-shirts'), ('pant-category', 'Pants'), ('Hoodie-category', 'Hoodies'), ('Shoes-category', 'Shoes')], max_length=40, null=True),
        ),
    ]
