# Generated by Django 3.0.8 on 2020-09-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_auto_20200912_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=True),
        ),
    ]
