# Generated by Django 3.0.8 on 2020-09-12 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0020_shipppingaddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShipppingAddress',
            new_name='ShippingAddress',
        ),
    ]
