# Generated by Django 3.0.8 on 2020-09-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0021_auto_20200912_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='order',
            field=models.ManyToManyField(null=True, to='shopping.Order'),
        ),
    ]
