# Generated by Django 3.0.8 on 2020-09-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0026_auto_20200919_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
