# Generated by Django 3.0.8 on 2020-09-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0027_shippingaddress_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='amount',
            field=models.CharField(max_length=100),
        ),
    ]
